/**
 * Lens / kubectl-derived table columns for built-in Kubernetes kinds.
 * Field paths follow the upstream API (many fields are root-level, not spec.*).
 */

const COL = {
  name: { id: 'name', label: 'Name', className: 'col-name', required: true },
  namespace: { id: 'namespace', label: 'Namespace', className: 'col-ns' },
  status: { id: 'status', label: 'Status', className: 'col-status' },
  age: { id: 'age', label: 'Age', className: 'col-age' },
  volume: { id: 'volume', label: 'Volume', className: 'col-volume' },
  capacity: { id: 'capacity', label: 'Capacity', className: 'col-capacity' },
  accessModes: { id: 'accessModes', label: 'Access Modes', className: 'col-access-modes' },
  storageClass: { id: 'storageClass', label: 'StorageClass', className: 'col-storage-class' },
  claim: { id: 'claim', label: 'Claim', className: 'col-claim' },
  keys: { id: 'keys', label: 'Keys', className: 'col-keys' },
  dataKeys: { id: 'dataKeys', label: 'Data Keys', className: 'col-data-keys' },
  secretType: { id: 'secretType', label: 'Type', className: 'col-secret-type' },
  scaleTarget: { id: 'scaleTarget', label: 'Reference', className: 'col-scale-target' },
  targets: { id: 'targets', label: 'Targets', className: 'col-targets' },
  minPods: { id: 'minPods', label: 'Min Pods', className: 'col-num' },
  maxPods: { id: 'maxPods', label: 'Max Pods', className: 'col-num' },
  hpaReplicas: { id: 'hpaReplicas', label: 'Replicas', className: 'col-num' },
  minAvailable: { id: 'minAvailable', label: 'Min Available', className: 'col-num' },
  maxUnavailable: { id: 'maxUnavailable', label: 'Max Unavailable', className: 'col-num' },
  allowedDisruptions: { id: 'allowedDisruptions', label: 'Allowed Disruptions', className: 'col-num' },
  holder: { id: 'holder', label: 'Holder', className: 'col-holder' },
  roles: { id: 'roles', label: 'Roles', className: 'col-roles' },
  version: { id: 'version', label: 'Version', className: 'col-version' },
  type: { id: 'type', label: 'Type', className: 'col-type' },
  reason: { id: 'reason', label: 'Reason', className: 'col-reason' },
  object: { id: 'object', label: 'Object', className: 'col-object-ref' },
  message: { id: 'message', label: 'Message', className: 'col-message' },
  lastSeen: { id: 'lastSeen', label: 'Last Seen', className: 'col-age' },
  secrets: { id: 'secrets', label: 'Secrets', className: 'col-num' },
  rules: { id: 'rules', label: 'Rules', className: 'col-num' },
  role: { id: 'role', label: 'Role', className: 'col-role' },
  subjects: { id: 'subjects', label: 'Subjects', className: 'col-num' },
  hard: { id: 'hard', label: 'Hard', className: 'col-hard' },
  limits: { id: 'limits', label: 'Limits', className: 'col-num' },
  value: { id: 'value', label: 'Value', className: 'col-num' },
  globalDefault: { id: 'globalDefault', label: 'Global Default', className: 'col-default-class' },
  handler: { id: 'handler', label: 'Handler', className: 'col-handler' },
  attacher: { id: 'attacher', label: 'Attacher', className: 'col-attacher' },
  pv: { id: 'pv', label: 'PV', className: 'col-pv' },
  attachRequired: { id: 'attachRequired', label: 'Attach Required', className: 'col-bool' },
  podInfoOnMount: { id: 'podInfoOnMount', label: 'Pod Info On Mount', className: 'col-bool' },
  storageCapacity: { id: 'storageCapacity', label: 'Storage Capacity', className: 'col-bool' },
  drivers: { id: 'drivers', label: 'Drivers', className: 'col-num' },
  group: { id: 'group', label: 'Group', className: 'col-api-group' },
  scope: { id: 'scope', label: 'Scope', className: 'col-scope' },
  service: { id: 'service', label: 'Service', className: 'col-service' },
  available: { id: 'available', label: 'Available', className: 'col-status' },
  webhooks: { id: 'webhooks', label: 'Webhooks', className: 'col-num' },
  failurePolicy: { id: 'failurePolicy', label: 'Failure Policy', className: 'col-policy-types' },
  matchConstraints: { id: 'matchConstraints', label: 'Match Constraints', className: 'col-targets' },
  policy: { id: 'policy', label: 'Policy', className: 'col-policy' },
  validationActions: { id: 'validationActions', label: 'Validation Actions', className: 'col-targets' },
}

const NAME_AGE = {
  columnOrder: ['name', 'age'],
  defaultVisible: ['name', 'age'],
  columns: { name: COL.name, age: COL.age },
}

/** kubectl-aligned schemas for kinds not defined inline in entityTableColumns.js */
export const BUILTIN_KIND_TABLE_SCHEMAS = {
  ReplicationController: {
    columnOrder: ['name', 'namespace', 'status', 'desired', 'current', 'ready', 'age'],
    defaultVisible: ['name', 'namespace', 'desired', 'current', 'ready', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      status: COL.status,
      desired: { id: 'desired', label: 'Desired', className: 'col-num' },
      current: { id: 'current', label: 'Current', className: 'col-num' },
      ready: { id: 'ready', label: 'Ready', className: 'col-num' },
      age: COL.age,
    },
  },
  PersistentVolumeClaim: {
    columnOrder: ['name', 'namespace', 'status', 'volume', 'capacity', 'accessModes', 'storageClass', 'age'],
    defaultVisible: ['name', 'namespace', 'status', 'volume', 'capacity', 'accessModes', 'storageClass', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      status: COL.status,
      volume: COL.volume,
      capacity: COL.capacity,
      accessModes: COL.accessModes,
      storageClass: COL.storageClass,
      age: COL.age,
    },
  },
  PersistentVolume: {
    columnOrder: ['name', 'capacity', 'accessModes', 'reclaimPolicy', 'status', 'claim', 'storageClass', 'age'],
    defaultVisible: ['name', 'capacity', 'accessModes', 'reclaimPolicy', 'status', 'claim', 'storageClass', 'age'],
    columns: {
      name: COL.name,
      capacity: COL.capacity,
      accessModes: COL.accessModes,
      reclaimPolicy: { id: 'reclaimPolicy', label: 'Reclaim Policy', className: 'col-reclaim-policy' },
      status: COL.status,
      claim: COL.claim,
      storageClass: COL.storageClass,
      age: COL.age,
    },
  },
  ConfigMap: {
    columnOrder: ['name', 'namespace', 'dataKeys', 'age'],
    defaultVisible: ['name', 'namespace', 'dataKeys', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      dataKeys: COL.dataKeys,
      age: COL.age,
    },
  },
  Secret: {
    columnOrder: ['name', 'namespace', 'secretType', 'keys', 'age'],
    defaultVisible: ['name', 'namespace', 'secretType', 'keys', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      secretType: COL.secretType,
      keys: COL.keys,
      age: COL.age,
    },
  },
  HorizontalPodAutoscaler: {
    columnOrder: ['name', 'namespace', 'scaleTarget', 'targets', 'minPods', 'maxPods', 'hpaReplicas', 'age'],
    defaultVisible: ['name', 'namespace', 'scaleTarget', 'targets', 'minPods', 'maxPods', 'hpaReplicas', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      scaleTarget: COL.scaleTarget,
      targets: COL.targets,
      minPods: COL.minPods,
      maxPods: COL.maxPods,
      hpaReplicas: COL.hpaReplicas,
      age: COL.age,
    },
  },
  PodDisruptionBudget: {
    columnOrder: ['name', 'namespace', 'minAvailable', 'maxUnavailable', 'allowedDisruptions', 'age'],
    defaultVisible: ['name', 'namespace', 'minAvailable', 'maxUnavailable', 'allowedDisruptions', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      minAvailable: COL.minAvailable,
      maxUnavailable: COL.maxUnavailable,
      allowedDisruptions: COL.allowedDisruptions,
      age: COL.age,
    },
  },
  Lease: {
    columnOrder: ['name', 'namespace', 'holder', 'age'],
    defaultVisible: ['name', 'namespace', 'holder', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      holder: COL.holder,
      age: COL.age,
    },
  },
  Node: {
    columnOrder: ['name', 'cpu', 'memory', 'disk', 'taints', 'roles', 'version', 'age', 'conditions'],
    defaultVisible: ['name', 'cpu', 'memory', 'disk', 'taints', 'roles', 'version', 'age', 'conditions'],
    columns: {
      name: COL.name,
      cpu: { id: 'cpu', label: 'CPU', className: 'col-node-cpu' },
      memory: { id: 'memory', label: 'Memory', className: 'col-node-memory' },
      disk: { id: 'disk', label: 'Disk', className: 'col-node-disk' },
      taints: { id: 'taints', label: 'Taints', className: 'col-num' },
      roles: COL.roles,
      version: COL.version,
      age: COL.age,
      conditions: { id: 'conditions', label: 'Conditions', className: 'col-node-conditions' },
    },
  },
  Event: {
    columnOrder: ['name', 'namespace', 'type', 'reason', 'object', 'message', 'lastSeen', 'age'],
    defaultVisible: ['name', 'namespace', 'type', 'reason', 'object', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      type: COL.type,
      reason: COL.reason,
      object: COL.object,
      message: COL.message,
      lastSeen: COL.lastSeen,
      age: COL.age,
    },
  },
  ServiceAccount: {
    columnOrder: ['name', 'namespace', 'secrets', 'age'],
    defaultVisible: ['name', 'namespace', 'secrets', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      secrets: COL.secrets,
      age: COL.age,
    },
  },
  Role: {
    columnOrder: ['name', 'namespace', 'rules', 'age'],
    defaultVisible: ['name', 'namespace', 'rules', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      rules: COL.rules,
      age: COL.age,
    },
  },
  ClusterRole: {
    columnOrder: ['name', 'rules', 'age'],
    defaultVisible: ['name', 'rules', 'age'],
    columns: {
      name: COL.name,
      rules: COL.rules,
      age: COL.age,
    },
  },
  RoleBinding: {
    columnOrder: ['name', 'namespace', 'role', 'subjects', 'age'],
    defaultVisible: ['name', 'namespace', 'role', 'subjects', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      role: COL.role,
      subjects: COL.subjects,
      age: COL.age,
    },
  },
  ClusterRoleBinding: {
    columnOrder: ['name', 'role', 'subjects', 'age'],
    defaultVisible: ['name', 'role', 'subjects', 'age'],
    columns: {
      name: COL.name,
      role: COL.role,
      subjects: COL.subjects,
      age: COL.age,
    },
  },
  ResourceQuota: {
    columnOrder: ['name', 'namespace', 'hard', 'age'],
    defaultVisible: ['name', 'namespace', 'hard', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      hard: COL.hard,
      age: COL.age,
    },
  },
  LimitRange: {
    columnOrder: ['name', 'namespace', 'limits', 'age'],
    defaultVisible: ['name', 'namespace', 'limits', 'age'],
    columns: {
      name: COL.name,
      namespace: COL.namespace,
      limits: COL.limits,
      age: COL.age,
    },
  },
  PriorityClass: {
    columnOrder: ['name', 'value', 'globalDefault', 'age'],
    defaultVisible: ['name', 'value', 'globalDefault', 'age'],
    columns: {
      name: COL.name,
      value: COL.value,
      globalDefault: COL.globalDefault,
      age: COL.age,
    },
  },
  RuntimeClass: {
    columnOrder: ['name', 'handler', 'age'],
    defaultVisible: ['name', 'handler', 'age'],
    columns: {
      name: COL.name,
      handler: COL.handler,
      age: COL.age,
    },
  },
  VolumeAttachment: {
    columnOrder: ['name', 'attacher', 'pv', 'node', 'status', 'age'],
    defaultVisible: ['name', 'attacher', 'pv', 'node', 'status', 'age'],
    columns: {
      name: COL.name,
      attacher: COL.attacher,
      pv: COL.pv,
      node: { id: 'node', label: 'Node', className: 'col-node' },
      status: COL.status,
      age: COL.age,
    },
  },
  CSIDriver: {
    columnOrder: ['name', 'attachRequired', 'podInfoOnMount', 'storageCapacity', 'age'],
    defaultVisible: ['name', 'attachRequired', 'podInfoOnMount', 'age'],
    columns: {
      name: COL.name,
      attachRequired: COL.attachRequired,
      podInfoOnMount: COL.podInfoOnMount,
      storageCapacity: COL.storageCapacity,
      age: COL.age,
    },
  },
  CSINode: {
    columnOrder: ['name', 'drivers', 'age'],
    defaultVisible: ['name', 'drivers', 'age'],
    columns: {
      name: COL.name,
      drivers: COL.drivers,
      age: COL.age,
    },
  },
  CustomResourceDefinition: {
    columnOrder: ['name', 'group', 'version', 'scope', 'age'],
    defaultVisible: ['name', 'group', 'version', 'scope', 'age'],
    columns: {
      name: COL.name,
      group: COL.group,
      version: COL.version,
      scope: COL.scope,
      age: COL.age,
    },
  },
  APIService: {
    columnOrder: ['name', 'service', 'available', 'age'],
    defaultVisible: ['name', 'service', 'available', 'age'],
    columns: {
      name: COL.name,
      service: COL.service,
      available: COL.available,
      age: COL.age,
    },
  },
  MutatingWebhookConfiguration: {
    columnOrder: ['name', 'webhooks', 'age'],
    defaultVisible: ['name', 'webhooks', 'age'],
    columns: { name: COL.name, webhooks: COL.webhooks, age: COL.age },
  },
  ValidatingWebhookConfiguration: {
    columnOrder: ['name', 'webhooks', 'age'],
    defaultVisible: ['name', 'webhooks', 'age'],
    columns: { name: COL.name, webhooks: COL.webhooks, age: COL.age },
  },
  ValidatingAdmissionPolicy: {
    columnOrder: ['name', 'failurePolicy', 'matchConstraints', 'age'],
    defaultVisible: ['name', 'failurePolicy', 'matchConstraints', 'age'],
    columns: {
      name: COL.name,
      failurePolicy: COL.failurePolicy,
      matchConstraints: COL.matchConstraints,
      age: COL.age,
    },
  },
  ValidatingAdmissionPolicyBinding: {
    columnOrder: ['name', 'policy', 'validationActions', 'age'],
    defaultVisible: ['name', 'policy', 'validationActions', 'age'],
    columns: {
      name: COL.name,
      policy: COL.policy,
      validationActions: COL.validationActions,
      age: COL.age,
    },
  },
  CSIStorageCapacity: { ...NAME_AGE },
  VolumeAttributesClass: { ...NAME_AGE },
  VerticalPodAutoscaler: { ...NAME_AGE },
}
