// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverMatches(arg1) {
  return window['go']['main']['App']['DiscoverMatches'](arg1);
}

export function GetCluster() {
  return window['go']['main']['App']['GetCluster']();
}

export function GetObjectDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetObjectDetails'](arg1, arg2, arg3);
}

export function GetView() {
  return window['go']['main']['App']['GetView']();
}

export function OpenKubeconfigDir() {
  return window['go']['main']['App']['OpenKubeconfigDir']();
}

export function OpenNewWindow(arg1) {
  return window['go']['main']['App']['OpenNewWindow'](arg1);
}

export function SelectContext(arg1) {
  return window['go']['main']['App']['SelectContext'](arg1);
}

export function SelectNamespace(arg1) {
  return window['go']['main']['App']['SelectNamespace'](arg1);
}

export function SetAutoRefresh(arg1) {
  return window['go']['main']['App']['SetAutoRefresh'](arg1);
}

export function SetKubeconfigPath(arg1) {
  return window['go']['main']['App']['SetKubeconfigPath'](arg1);
}

export function StartInvestigation(arg1) {
  return window['go']['main']['App']['StartInvestigation'](arg1);
}

export function StopInvestigation() {
  return window['go']['main']['App']['StopInvestigation']();
}

export function SyncCluster() {
  return window['go']['main']['App']['SyncCluster']();
}
