// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function DiscoverMatches(arg1) {
  return window['go']['main']['App']['DiscoverMatches'](arg1);
}

export function GetCluster() {
  return window['go']['main']['App']['GetCluster']();
}

export function GetClusterStatus() {
  return window['go']['main']['App']['GetClusterStatus']();
}

export function GetObjectDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetObjectDetails'](arg1, arg2, arg3);
}

export function GetResourceCatalog(arg1) {
  return window['go']['main']['App']['GetResourceCatalog'](arg1);
}

export function GetTerminalShellChoices() {
  return window['go']['main']['App']['GetTerminalShellChoices']();
}

export function GetView() {
  return window['go']['main']['App']['GetView']();
}

export function ListCatalogEntities(arg1) {
  return window['go']['main']['App']['ListCatalogEntities'](arg1);
}

export function LogTailActive() {
  return window['go']['main']['App']['LogTailActive']();
}

export function OpenKubeconfigDir() {
  return window['go']['main']['App']['OpenKubeconfigDir']();
}

export function OpenNewWindow(arg1) {
  return window['go']['main']['App']['OpenNewWindow'](arg1);
}

export function PauseLogTail() {
  return window['go']['main']['App']['PauseLogTail']();
}

export function RefreshResourceCatalog(arg1) {
  return window['go']['main']['App']['RefreshResourceCatalog'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function ResumeLogTail() {
  return window['go']['main']['App']['ResumeLogTail']();
}

export function SelectContext(arg1) {
  return window['go']['main']['App']['SelectContext'](arg1);
}

export function SelectNamespace(arg1) {
  return window['go']['main']['App']['SelectNamespace'](arg1);
}

export function SetAutoRefresh(arg1) {
  return window['go']['main']['App']['SetAutoRefresh'](arg1);
}

export function SetKubeconfigPath(arg1) {
  return window['go']['main']['App']['SetKubeconfigPath'](arg1);
}

export function SetPollEverySec(arg1) {
  return window['go']['main']['App']['SetPollEverySec'](arg1);
}

export function StartInvestigation(arg1) {
  return window['go']['main']['App']['StartInvestigation'](arg1);
}

export function StartLogTail(arg1) {
  return window['go']['main']['App']['StartLogTail'](arg1);
}

export function StartTerminal(arg1) {
  return window['go']['main']['App']['StartTerminal'](arg1);
}

export function StopInvestigation() {
  return window['go']['main']['App']['StopInvestigation']();
}

export function StopLogTail() {
  return window['go']['main']['App']['StopLogTail']();
}

export function SyncCluster() {
  return window['go']['main']['App']['SyncCluster']();
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
