// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';
import {kube} from '../models';
import {details} from '../models';
import {api} from '../models';

export function DiscoverMatches(arg1:main.DiscoverOptions):Promise<Array<model.MatchedObject>>;

export function GetCluster():Promise<kube.ClusterState>;

export function GetObjectDetails(arg1:string,arg2:string,arg3:string):Promise<details.ObjectDetail>;

export function GetView():Promise<api.View>;

export function OpenKubeconfigDir():Promise<void>;

export function OpenNewWindow(arg1:main.OpenWindowOptions):Promise<void>;

export function SelectContext(arg1:string):Promise<kube.ClusterState>;

export function SelectNamespace(arg1:string):Promise<kube.ClusterState>;

export function SetAutoRefresh(arg1:boolean):Promise<void>;

export function SetKubeconfigPath(arg1:string):Promise<kube.ClusterState>;

export function StartInvestigation(arg1:main.StartOptions):Promise<void>;

export function StopInvestigation():Promise<void>;

export function SyncCluster():Promise<kube.ClusterState>;
